bazeltools/bazel-deps

- 3rdparty/jvm/com/fasterxml/jackson/core/BUILD
- 3rdparty/jvm/com/fasterxml/jackson/dataformat/BUILD
- 3rdparty/jvm/com/google/guava/BUILD
- 3rdparty/jvm/io/circe/BUILD
- 3rdparty/jvm/javax/enterprise/BUILD
- 3rdparty/jvm/org/apache/httpcomponents/BUILD
- 3rdparty/jvm/org/apache/maven/BUILD
- 3rdparty/jvm/org/eclipse/aether/BUILD
- 3rdparty/jvm/org/eclipse/sisu/BUILD
- 3rdparty/jvm/org/scalacheck/BUILD
- 3rdparty/jvm/org/slf4j/BUILD
- 3rdparty/jvm/org/typelevel/BUILD
- README.md
- dependencies.yaml
- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
> Support runtime_deps rather than exports for maven deps

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
You can add a list of `UnversionedCoordinates` with:
```yaml
com.group:
artifact:
lang: java
exclude: ["foo:bar", "baz:boom"]
```
> Add support for exclude in dependencies

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
Many times we might have several lines. This makes it cleaner to write.
> Make buildHeader a list of strings

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
> Fix an issue with subproject merging

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/FormatDeps.scala
- src/scala/com/github/johnynek/bazel_deps/MergeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/ParseProject.scala
this is untested except at the repl... :(
But seems to be working and fits a need so I'm willing to merge and take the test coverage deficit.
> Add merge command

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MergeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/ParseProject.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
This is a feature request from @non
> Add a command to add a dependency

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
I noticed a regression in formatting after running the latest internally.
The bug would probably have bitten us sooner or later.
cc @mikemintz
> Maximize the name of a project

- src/scala/com/github/johnynek/bazel_deps/IO.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
> Create an empty BUILD file in the 3rdparty/sha-file directory during generate step

- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
Currently, if artifact B has a dependency A with version `1.0` while artifact C has a dependency A with version `2.0`, as well as B and C are explicitly added in the yaml while A is not, this tool will generate A with version `2.0` because of the `highest` mode of conflict resolutions. If I want A with version `1.0`, I would like to add option `exclude` to C to exclude its dependency A just as the conflict resolution in maven. But this tool will only exclude A in the `exports` in `java_library` of C because it does not add A to exclusions to collect dependencies. As a result, finally this tool will still take the highest version of A which C wants. So this PR is to add exclusions to collect dependencies. 
For example, `net.sf.ezmorph:ezmorph:1.0.6` has a dependency …
> Add exclusions to collect dependencies

- 3rdparty/workspace.bzl
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
In case of depenency conflicts output more detailed information about
which depenency requested which version.
This makes resolving dependency conflicts easier.
> Add detailed output about dependency conflicts

- 3rdparty/workspace.bzl
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
Fixes #116.
This didn't seem to touch any tests. Is that expected, or should I be doing something more than `bazel test //...`?
> Add header comment to generated workspace.bzl

- src/scala/com/github/johnynek/bazel_deps/Normalizer.scala
- test/scala/com/github/johnynek/bazel_deps/NormalizerTest.scala
Dependency loops in transitive dependencies previously caused an infinite loop
in the Normalizer; now they don't. This behavior wasn't present for explicitly-
listed dependencies. Those did (and still do) pass through Normalizer.scala
and blow up in Writer.scala.
> Fix for infinite loop in Normalizer.java in transitive deps

- src/scala/com/github/johnynek/bazel_deps/AetherResolver.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
this sets us up for #145.
If we merge this first, hooking coursier in becomes trivial.
review @non ?
> factor MakeDeps to support general execution environments

- src/scala/com/github/johnynek/bazel_deps/CoursierResolver.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD
- test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
fixes #149 
Not sure why this is needed since we are communicating excludes to coursier, but it seems like it wouldn't hurt to make sure we don't put the edges in the final graph.
@roblg please take a look
cc @ianoc-stripe maybe this fixes our issues as well?
> add a test to fix some excludes on Coursier

- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD
- test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
@ianoc-stripe noticed an infinite loop in #162.
The bug can be fixed by tracking for each node if we are working on it, and if so, who depends on it. If we find a loop, we stop and report the loop.
Adding the error handling complicates it quite a bit, but we should be handling this error in a nice way rather than a stack overflow.
> Check for loops in the export graph

- WORKSPACE
scala_register_toolchains is loaded and called just a few lines below
> Drop duplicate lines

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
e.g. `lombok` needs `generates_api = True`.
> add generatesApi support for java_plugin

- README.md
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
Thanks for all the work, the project is great!
As requested in #171 
If desirable I can add a test case that verifies the default options are as stated in the docs.
> Change default resolverType to coursier

- src/scala/com/github/johnynek/bazel_deps/Writer.scala
> Support pom-only java dependencies

- README.md
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
Allows for specifying a custom filename as the filename for generated build files.
Resolves  #111
> Add option for custom build file name

- README.md
Document the options that are accepted in the dependencies file. Also
add syntax highlighting to code sections that were missing them.
> Document `options`

- .bazel-installer-linux-x86_64.sh.sha256
- .travis.yml
- WORKSPACE
Support for current bazel release
> Upgrade to bazel 0.27

- .github/workflows/release.yml
- README.md
- WORKSPACE
- ci_scripts/make_native_artifact.sh
- ci_scripts/make_update_dependencies.sh
- ci_scripts/make_update_maven_deps.sh
- ci_scripts/prepare_output.sh
1. Include sha 256's in the outputs
2. Add a bash script that you can use to get started pre-loaded with the URL's and hashes to download things
3. Update the readme with a quick start flow using this stuff to get going.
> Add some more polish around the usage of the native images

- ci_scripts/make_update_dependencies.sh
I haven't actually seen this build or run yet
> Add mkdir to update_dependencies.sh

- 3rdparty/workspace.bzl
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/templates/jar_artifact_backend.bzl
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
This is useful to access private repositories. 
Also support a `$env_var` format for better flexibility
> Add authentication file support

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
Fixes Issue https://github.com/bazeltools/bazel-deps/issues/325
Ran all unit test cases
```
bazel-deps git:(revert_deleted_options) bazel test //...
INFO: Analyzed 102 targets (0 packages loaded, 0 targets configured).
INFO: Found 94 targets and 8 test targets...
INFO: Elapsed time: 28.071s, Critical Path: 27.96s
INFO: 12 processes: 1 internal, 5 darwin-sandbox, 6 worker.
INFO: Build completed successfully, 12 total actions
//test/scala/com/github/johnynek/bazel_deps:graphtest           (cached) PASSED in 2.6s
//test/scala/com/github/johnynek/bazel_deps:modeltest           (cached) PASSED in 1.2s
//test/scala/com/github/johnynek/bazel_deps:normalizertest      (cached) PASSED in 1.1s
//test/scala/com/github/johnynek/bazel_deps:coursier_test                PASSED in 21.8s …
```
> Revert deleted options

- ci_scripts/make_native_artifact.sh
> Fix graal version in ci_scripts

- dependencies.yaml
- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/FS.scala
- src/scala/com/github/johnynek/bazel_deps/FormatDeps.scala
- src/scala/com/github/johnynek/bazel_deps/GradleResolver.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/MergeDeps.scala
> use cats effect with fs

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
it's a little silly, but this appears to work for me
> Enable bazel-deps to fetch scala3 artifacts

- src/scala/com/github/johnynek/bazel_deps/CreatePom.scala
- test/scala/com/github/johnynek/bazel_deps/CreatePomTest.scala
also remove xml literals from the main code which have been removed from scala.
> Don't emit type in pom if it is a jar

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
**Problem/Solution**
This adds dependabot configuration to update GitHub Actions automatically.
> Update GitHub Actions automatically

- src/scala/com/github/johnynek/bazel_deps/Writer.scala
one or all of these nodes should be the problem you need to deal with.
> Show the nodes that depend on root of a loop

- src/scala/com/github/johnynek/bazel_deps/AetherResolver.scala
- src/scala/com/github/johnynek/bazel_deps/CoursierResolver.scala
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/GradleLockDependency.scala
- src/scala/com/github/johnynek/bazel_deps/GradleResolver.scala
- src/scala/com/github/johnynek/bazel_deps/Graph.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
- src/scala/com/github/johnynek/bazel_deps/TryMerge.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD.bazel
- test/scala/com/github/johnynek/bazel_deps/GradleResolverTest.scala
- test/scala/com/github/johnynek/bazel_deps/GraphPropTest.scala
- test/scala/com/github/johnynek/bazel_deps/WriterTest.scala
I didn't find any smoking gun errors, and couldn't seem to actually reproduce the error we saw.
From my tests, it *seems* like the code is working.
This PR mainly does 3 things:
1. simplifies the code and modernizes some syntax
2. adds tests for gradle resolvers especially exercising ignoring edges
3. changes the Writer to emit *all* (not just the first) error it finds.
>  gradle resolver refactors
