- 3rdparty/jvm/com/chuusai/BUILD
- 3rdparty/jvm/com/github/mpilquist/BUILD
- 3rdparty/jvm/org/typelevel/BUILD
- 3rdparty/workspace.bzl
- dependencies.yaml
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Normalizer.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
This allows you to specify a dependency that should be found in the final normalized transitive graph, and set attributes (language being the only thing now). This comes up with scala deps not being clearly scala dependencies, so we need to mark them as such in some cases.
> Support unversioned deps

- src/scala/com/github/johnynek/bazel_deps/IO.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
rather than store the strings we want to write in our IO.Result, use Eval so we can generate as needed (since we generally only need them one time, and we could GC immediately after writing).
> use Eval to use less memory

- WORKSPACE
this bumps to: https://github.com/bazelbuild/rules_scala/pull/85 to work around an issue for a user.
> use later bazel-deps to fix long file name issue

- .travis.yml
- src/scala/com/github/johnynek/bazel_deps/IO.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
This nukes the thirdparty directory on each run so that stale references don't stick around.
Clearly this means you need to be using this tool with a version control system.
> nuke thirdparty on run

- 3rdparty/jvm/asm/BUILD
- 3rdparty/jvm/com/chuusai/BUILD
- 3rdparty/jvm/com/fasterxml/jackson/core/BUILD
- 3rdparty/jvm/com/fasterxml/jackson/dataformat/BUILD
- 3rdparty/jvm/com/github/mpilquist/BUILD
- 3rdparty/jvm/com/google/code/findbugs/BUILD
- 3rdparty/jvm/com/google/guava/BUILD
- 3rdparty/jvm/commons_codec/BUILD
- 3rdparty/jvm/io/circe/BUILD
- 3rdparty/jvm/javax/annotation/BUILD
- 3rdparty/jvm/javax/enterprise/BUILD
- 3rdparty/jvm/org/apache/httpcomponents/BUILD
- 3rdparty/jvm/org/apache/maven/BUILD
- 3rdparty/jvm/org/codehaus/plexus/BUILD
- 3rdparty/jvm/org/eclipse/aether/BUILD
- 3rdparty/jvm/org/eclipse/sisu/BUILD
- 3rdparty/jvm/org/rogach/BUILD
- 3rdparty/jvm/org/scala_lang/BUILD
- 3rdparty/jvm/org/scala_lang/modules/BUILD
- 3rdparty/jvm/org/scala_sbt/BUILD
- 3rdparty/jvm/org/scalacheck/BUILD
- 3rdparty/jvm/org/slf4j/BUILD
- 3rdparty/jvm/org/spire_math/BUILD
- 3rdparty/jvm/org/typelevel/BUILD
- 3rdparty/jvm/org/yaml/BUILD
- WORKSPACE
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
This cleans up the generation of BUILD files and makes them closer, but not maybe yet exactly, what https://github.com/bazelbuild/buildtools would do.
It would be nice to generate something that is transparent to buildifier (which is basically implementing half of buildifier, the other half being a parser).
> Use paiges to generate BUILD files

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Graph.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Normalizer.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD
- test/scala/com/github/johnynek/bazel_deps/NormalizerTest.scala
This adds a test for a bug we observed in how we
rewrite the Normalized graph. The old algorithm
had bugs and was more complex. The current algorithm
builds up the final graph by starting at the roots
with the normalized versions of anything reachable.
> Change the Normalization algorithm

- README.md
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
Previously, the resolver cached packages in `target/local-repo` in the current working directory.  Now, two behaviors
are available via the `resolverCache` option:
- `local`: This is the existing behavior and the new default.
- `bazel_output_base`: Cache packages to `bazel-deps/local-repo` inside the current project's Bazel output base.  This
path is resolved by running `bazel info output_base` for the project passed as `--repo-root`.  This path has the
benefit of surviving `git clean -x`, but can still be removed with `bazel clean --expunge`.
> New option to configure the path where bazel-deps will cache resolved packages

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
A trailing hyphen should not be appended if there is no subproject name; doing so generates an invalid artifact.
I don't think this fixes all of #44 but only the second part that I reported as #57, but I can't repro it to test for sure.
> properly handle empty subproject when flattening dependencies (fixes #57)

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
This should fix #44 
The algorithm got a lot more expensive and complex, but describing it is easy: we merge submodules by taking the biggest group we can make first. After that, if two are the same size we sort by the rest of the record.
This seems to solve the problems we have.
cc @mikemintz
> Fix a bug with yaml minimization

- 3rdparty/load.bzl
- 3rdparty/workspace.bzl
- README.md
- WORKSPACE
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
When turned on, a user doesn't have to provide a callback when calling maven_dependencies() from their WORKSPACE file.
Instead, maven_dependencies() will call a function defined in the same .bzl file that calls native.maven_jar() or equivalent.
The goal is to simplify setting up a project to work with bazel-deps.
Fixes #60 .
> New flag: --inline-callback obviates load.bzl

- README.md
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Label.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
My particular use case of this is having two dependencies.yaml files in the same repository, with different versions of certain artifacts and different `thirdPartyDirectory`s.  Without this prefixing, the names used in the workspace and for `bind` conflict.
> add support for namePrefix option, to avoid conflicts with generated names

- WORKSPACE
This is needed to support the newer bazel's around the shapeless implicits. (Fixed in shapeless too, but this will sort here).
> Bump scala rules version

- WORKSPACE
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseGeneratedDocTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestUtil.scala
@ianoc-stripe in #84 found an example of the minimization algorithm deleting entries.
I have reworked the algorithm again to be more principled, but also exponential in complexity. The exponential part only runs for sets of dependencies that share a common prefix in maven group and in artifact, so in practice that is small enough that it is very fast. But if you have 100 modules in a single artifact each with different versions, this algorithm might fall over.
It is only used in format now, so even if we hit such a corner case, users can work around by not formatting (which triggers the minimization).
> Improve the yaml minimization algorithm (again).

- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/IO.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
If present, this flag causes the generate command to resolve all dependencies as usual, but does not write the files. Instead, it checks that each generated file on disk has the expected content.  If any files do not match the expected content, they are logged and bazel-deps exits with code 2; bazel-deps exits 0 if everything matches.
> add `--check-only` flag to `generate` command (fixes #85)

- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
If present, the contents of each generated BUILD file will be formatted before writing to disk (or checking against the existing files).  Formatting takes just a couple milliseconds per file.
I think this approach gives the best flexibility of not adding a hard dependency on the buildifier.  Simply running the buildifier after generate in a wrapper script isn't sufficient, because the in-memory versions used by `--check-only` need to be formatted like the files on disk.  This covers both.
> add `--buildifier` option to `generate` to format BUILD files (fixes #73)

- .bazel-installer-linux-x86_64.sh.sha256
- .travis.yml
- WORKSPACE
The latest version of `rules_scala` supports Bazel 0.7.0. 
The `master` version of `bazel-deps` fails with Bazel 0.7.0:
```
gdonovan@3983:~/development/bazel-deps (master)$ bazel build //... && bazel test --test_output errors //... && bazel build src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar && ./gen_maven_deps.sh generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml && git diff --exit-code
ERROR: /Users/gdonovan/development/bazel-deps/3rdparty/jvm/org/typelevel/BUILD:87:1: in scala_library rule //3rdparty/jvm/org/typelevel:macro_compat: 
Traceback (most recent call last):
File "/Users/gdonovan/development/bazel-deps/3rdparty/jvm/org/typelevel/BUILD", line 87
scala_library(name = 'macro_compat')
File …
```
> Support Bazel 0.7.0 with rules_scala.

- README.md
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
See discussion in https://github.com/johnynek/bazel-deps/issues/62
I added support for multiple annotation processors per `java_library`, as I think it is a possible (though admittedly rare) requirement.
There are a couple TODOs and I would like to add test coverage to the new functions in `Target` but I wanted to start a PR to see if this was directionally correct.
> Support annotation processors

- 3rdparty/jvm/org/scala_lang/BUILD
- 3rdparty/jvm/org/scala_lang/modules/BUILD
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
This fixes https://github.com/johnynek/bazel-deps/issues/103 by exporting the replacement target instead of including it as a jar.
A snippet of a diff after running this version of `bazel-deps` in our monorepo:
```
diff --git a/3rdparty/jvm/io/getquill/BUILD b/3rdparty/jvm/io/getquill/BUILD
index 8dc63b848..12cbda461 100644
--- a/3rdparty/jvm/io/getquill/BUILD
+++ b/3rdparty/jvm/io/getquill/BUILD
@@ -3,20 +3,20 @@ load("@io_bazel_rules_scala//scala:scala_import.bzl", "scala_import")
scala_import(
name = "quill_cassandra",
-    jars = [
-        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
-    ],
visibility = [
"//visibility:public",
],
+    exports = [
+        "//3rdparty/jvm_manual/io/getquill:quill_cassandra",
+    ],
)
scala_import(
name = "quill_core",
-    jars = [
- …
```
> Export target in replacement.

- 3rdparty/manual/BUILD.decline
- 3rdparty/manual/BUILD.paiges
This fixes the build w/ bazel 0.10.0. Bazel commit https://github.com/bazelbuild/bazel/commit/c93ef7ba6443d7546294eacfe9d21573a11aad70 changed the behavior of prelude_bazel such that it doesn't apply to dependency workspaces -- those workspaces use their own prelude_bazel if they have one.
> Fixes #112 -- build broken under bazel 0.10.0

- BUILD
- README.md
Instead of running `gen_maven_deps.sh`, `bazel run` will build the necessary deps and run `parseproject` as though it was a deploy jar (but not really, it's a stub script that knows where the runfiles are). This removes the need for a separate build step and a shell script runner. 
I've also created a top level alias for `parseproject` to not have to refer a deeply nested target. I think this makes the final command simpler: `bazel run //:parse -- ...args`
> Simplify usage instructions to use bazel run on a top level alias

- src/scala/com/github/johnynek/bazel_deps/Resolver.scala
In Resolver.scala a SHA1 value was validated using:
scala.math.BigInt(hexString,16).asByteArray.length == 20.
This does not work if the SHA1 value starts with a high order bit, i.e, 8-f.
In that case the byte array representation of the BigInt has an additional sign
byte and the length of the byte array is 21.
The fix is to switch from using BigInt for validation of SHA1 values to a
simple syntactic check on the string, i.e., each character is in [0-9A-Fa-f]
and the lengt of the string is 40.
This fixes #120.
> Fix SHA1 check

- ij.bazelproject
One click setup for IntelliJ developers with the Bazel plugin using "Import project view file" option.
> Add .bazelproject file for easy IntelliJ setup

- README.md
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
https://docs.bazel.build/versions/master/be/functions.html#licenses
If you put your BUILD files under third_party, bazel will throw an error
if there is no license tag.
Licenses are defined in the options section, as a Set[String]. It's a
global setting for now.
> Add the ability to add licenses tags to generated BUILD files.

- 3rdparty/workspace.bzl
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
This fixes the order of the dependency comments from #105 to minimize unnecessary changes in `git diff`.
I picked string sort order arbitrarily to enforce _some_ ordering, but I don't actually feel strongly about what the ordering is. Happy to change it to whatever.
> Fix order of dependency comments in .bzl file

- .travis.yml
- WORKSPACE
- dependencies.yaml
- src/scala/com/github/johnynek/bazel_deps/FormatDeps.scala
When running `format-deps` the formatted `dependencies.yaml` will have lines containing only whitespace. This makes those lines empty.
The update to `paiges` uses the [v0.2.1 tag](https://github.com/typelevel/paiges/tree/v0.2.1) to include the fix to trimming in typelevel/paiges#80.
> Trim empty lines.

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/IO.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/ParseProject.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
We were already including an SLF4J dependency, so all we had to do was
to start using it! This commit adds a Verbosity type, along with the
Decline machinery to be able to pass log levels as command-line
arguments.
In the future we should add verbosity to the other bazel-deps
commands, and replace all error/info reporting println's with logging
instead. (Some println's represent program output; these should
probably stay as-is.)
> Use SLF4J logging in MakeDeps and related code.

- README.md
- src/scala/com/github/johnynek/bazel_deps/AetherResolver.scala
- src/scala/com/github/johnynek/bazel_deps/CoursierResolver.scala
- src/scala/com/github/johnynek/bazel_deps/Decoders.scala
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Label.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
- test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
Sorry for the churn on this. This is based on my comments in https://github.com/johnynek/bazel-deps/issues/69#issuecomment-372370151, and works on our codebase, and should work for multiple classifers. It supports the "front half" of specifying packaging and classifiers. (Classifiers should "just work", but there's no work done yet to distinguish between `jar` packaging and non-`jar` packaging in the BUILD files, so if you depend on a non-jar package, I believe the BUILD files will be broken.
* this works on our codebase. The only change is the addition of packaging+classifier
in target names and bind
* needs some real tests
* needs consensus on the palatability of this .yaml syntax
* I probably broke scala somehow
* I snuck in support for `exclude` of particular packaging/classifiers …
> Supporting classifiers and packaging in ArtifactOrProject

- src/scala/com/github/johnynek/bazel_deps/CoursierResolver.scala
Otherwise, only compile-scoped dependencies are included.  See this comment for details: https://github.com/coursier/coursier/issues/552#issuecomment-310133532
> coursier: set Dependency.configuration appropriately to include runtime-scoped dependencies (fixes #156)

- 3rdparty/jvm/com/fasterxml/jackson/core/BUILD
- 3rdparty/jvm/com/google/guava/BUILD
- 3rdparty/jvm/commons_codec/BUILD
- 3rdparty/jvm/io/circe/BUILD
- 3rdparty/jvm/org/apache/commons/BUILD
- 3rdparty/jvm/org/apache/httpcomponents/BUILD
- 3rdparty/jvm/org/apache/maven/BUILD
- 3rdparty/jvm/org/codehaus/plexus/BUILD
- 3rdparty/jvm/org/eclipse/aether/BUILD
- 3rdparty/jvm/org/scala_lang/BUILD
- 3rdparty/jvm/org/scala_lang/modules/BUILD
- 3rdparty/jvm/org/scala_sbt/BUILD
- 3rdparty/jvm/org/slf4j/BUILD
- 3rdparty/jvm/org/spire_math/BUILD
- 3rdparty/jvm/org/typelevel/BUILD
- 3rdparty/jvm/org/yaml/BUILD
- 3rdparty/workspace.bzl
- README.md
- dependencies.yaml
- src/scala/com/github/johnynek/bazel_deps/Label.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
This solves issue #99  (again)...
Sadly, I had lost track that @arjantop had already submitted a PR on this. I apologize. I took a slightly different take, but not much different. That said, looking back, I like this a bit better: keeping Target more generic and keeping the smarts about setting visibility in Writer, which is already keeping state about how to map maven dependency graphs into bazel.
Currently, it is always on. I could make it an option, but I am on the fence about that. I think maybe an option to turn it off, but by default require it.
We have seen several issues with people using incidental transitive dependencies that break when we update versions.
This required several rounds to update even this small repo, so it probably means that upgrading a big repo will require an …
> Strict visibility for generated dependencies

- src/scala/com/github/johnynek/bazel_deps/IO.scala
String.split takes a regular expression as the pattern for splitting. On Windows, paths contain backslashes as directory separators. However, backslashes are special characters in a regex so the pattern will be invalid. I have fixed this by quoting the pattern.
> Fix regex quoting issue that prevents it working on Windows

- 3rdparty/workspace.bzl
- src/scala/com/github/johnynek/bazel_deps/templates/jar_artifact_backend.bzl
This can then be used by something like
https://github.com/google/bazel-common/blob/master/tools/maven/pom_file.bzl
to know the imported maven dependencies when writing their OWN poms.
> Include a tag with the jar's maven_coordinates

- src/scala/com/github/johnynek/bazel_deps/CoursierResolver.scala
The following improvements reduce the runtime from 22m to 4m on the main scala repo at Stripe with a cold coursier cache.
While investigating performance of the `generate` command I noticed that threads were being under utilized. Here is an image of thread usage during a typical run:
As you can see, `pool-1-thread-*` threads appear to be executing sequentially. A thread dump revealed that these threads were fetching artifacts and calculating SHAs. I tracked this behavior down to a `traverse` on a list of Tasks, which serializes all of the tasks (Thanks to @ianoc for the tip here). Now [Task.gather](https://github.com/coursier/coursier/blob/master/cache/shared/src/main/scala/coursier/util/TaskGather.scala#L10), a parallel traverse from coursier, is used to parallelize these operations. You …
> Improve performance by fetching artifacts in parallel and fixing SHA-1 downloads

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
We really need a principled way to format these files, but in the meantime we need a way that doesn't take a ridiculous amount of time. This PR reduces the `format-deps` step for one of our internal repositories from ~10+ minutes to a few seconds with no semantic change.
r? @oscar-stripe
> Another attempt to fix bad cases here

- WORKSPACE
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
Some corporate firewalls might block the 'old school' git protocol. Using HTTPS for best compatibility.
> Change git_repository URLs to use 'https' schema

- src/scala/com/github/johnynek/bazel_deps/BUILD
Fixes
```
$ bazel run //:parse -- generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml
ERROR: /Users/tekumara/code3/bazel-deps/src/scala/com/github/johnynek/bazel_deps/BUILD:160:38: Traceback (most recent call last):
File "/Users/tekumara/code3/bazel-deps/src/scala/com/github/johnynek/bazel_deps/BUILD", line 152
scala_binary(name = "parseproject", srcs = ["Pa..."], <5 more arguments>)
File "/Users/tekumara/code3/bazel-deps/src/scala/com/github/johnynek/bazel_deps/BUILD", line 160, in scala_binary
PACKAGE_NAME
The value 'PACKAGE_NAME' has been removed in favor of 'package_name()', please use the latter (https://docs.bazel.build/versions/master/skylark/lib/native.html#package_name). You can temporarily allow the old name by using --incompatible_package_name_is_a_function=false …
```
> Fix PACKAGE_NAME error

- src/scala/com/github/johnynek/bazel_deps/AetherResolver.scala
Configure Aether to not use repositories definied in pom.xml for dependency
resolution of transitives. This prevents Aether from reaching out to external
repos which might be blocked by corporate firewall.
Signed-off-by: Gunnar Wagenknecht <gwagenknecht@salesforce.com>
> Ignore POM defined repositories during Aether resolution

- README.md
- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- src/scala/com/github/johnynek/bazel_deps/maven/Tool.scala
- test/scala/com/github/johnynek/bazel_deps/ModelGenerators.scala
- test/scala/com/github/johnynek/bazel_deps/ModelTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTest.scala
- test/scala/com/github/johnynek/bazel_deps/ParseTestCasesTest.scala
related to #68.
Adding an option to generate a dependency with `neverlink` option.
The reason why I duplicate each target with `neverlink` option is to allow using neverlink option on a specific build targets while other build targets could use the regular dependency target.
> add neverlink option

- README.md
Instructions in `README.md` currently won't work because `//:parse` doesn't build the deploy JAR that `gen_maven_deps.sh` looks for.
> Update README to fix broken instructions

- README.md
Coursier seems to ignore the `resolverCache` option, which makes it
harder to work out how to clear the cache.
> Document Coursier cache path

- src/scala/com/github/johnynek/bazel_deps/Label.scala
In a case of an empty third party directory, we'll
get visilibity  of ":__subpackages__" which will
deny access from higher packages in the same third
party directory. This is an attempt to fix that.
> Label -> fromRoot: add // before empty root

- src/scala/com/github/johnynek/bazel_deps/Label.scala
**Note:** Previously this change request was opened as https://github.com/johnynek/bazel-deps/pull/266, but I'm redoing it to avoid using my fork's `master` branch. 
----
Extra conditional to fix bug intro'd by https://github.com/johnynek/bazel-deps/pull/251
This change was originally suggested by @Reflexe in the thread, but they didn't make a PR for it. https://github.com/johnynek/bazel-deps/compare/master...Reflexe:master
> Fix small bug intro'd in PR #251 

- WORKSPACE
Trying to pull in https://github.com/bazelbuild/rules_scala/pull/920
Changes since the last update:
https://github.com/bazelbuild/rules_scala/compare/0f89c21...a676633
> Update rules_scala to pull in https for central.maven.org

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
[Given that maven now requires all requests to be made over `HTTPS`](https://support.sonatype.com/hc/en-us/articles/360041287334), update the default resolver accordingly to use https://repo.maven.apache.org/maven2/.
> Make https://repo.maven.apache.org/maven2/ the default resolver URL

- .bazelrc.github
- .github/workflows/release.yml
- .gitignore
- README.md
- ci_scripts/bootstrapping_bazel
- ci_scripts/build_fat_jar.sh
- ci_scripts/ci_install_bazel.sh
- ci_scripts/make_native_artifact.sh
- ci_scripts/reflection.json
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
Looks like its working -- I have the build run a native image on each platform then ensure it can resolve the bazel deps own dependencies
Need to add some comments, but I've seen the thing in the Writer.scala before, somehow the `Source.from` API does not work well with native images, seen this loading files in the past. No idea why though -- its unreliable and works sometimes.
https://github.com/ianoc/bazel-deps/releases
> Add's some GitHub Actions configuration and produces linux + Mac native images

- .github/workflows/release.yml
The workflow shouldn't happen on pull requests or non master branches
> Stop the workflow from running on non master

- ci_scripts/make_update_dependencies.sh
Currently if the `else` branch is run bash will attempt to run the string as a command.
> Fix 'else' branch of conditional in update_dependencies.sh

- .github/workflows/release.yml
Github deprecated some methods for security. So just need to bump this dep to allow it to keep working.
> Update the setup scala for changes in github

- src/scala/com/github/johnynek/bazel_deps/DepsModel.scala
This fixes #298.
New behavior does not drop `generateNeverlink` during formatting.
> Include generateNeverlink in format-deps (#298)

- 3rdparty/jvm/org/scala_lang/BUILD
- 3rdparty/jvm/org/scala_lang/modules/BUILD
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
Fixes https://github.com/johnynek/bazel-deps/issues/173
For targets specified under `replacements`, this makes the corresponding `3rdparty/jvm` targets have public visibility.
This addresses behavior that I've found to be counterintuitive with `strictVisibility` enabled. I'd expect all dependencies declared in a `dependencies.yaml` to be visible to the workspace, regardless of whether it's under `dependencies` or `replacements`.
> Make targets for replacements have public visibility

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/CreatePom.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD
- test/scala/com/github/johnynek/bazel_deps/CreatePomTest.scala
The reason for this PR is to allow for Dependabot scanning on JVM repositories that use Bazel. Dependabot is used to scan repositories for vulnerable dependencies. However, the tool only checks dependencies listed in pom.xml files. 
An [initial design](https://github.com/johnynek/bazel-deps/pull/307) was to add this functionality as its own command. Since the Generate command already parses the `dependencies.yaml` and resolves versions for transitive dependencies, the Generate command was extended. When a `pomFile` option is passed to Generate,  a`pom.xml` file will be created alongside bazel targets.
Example
```
bazel run //:parse -- generate -r `pwd` -s 3rdparty/workspace.bzl -d dependencies.yaml --pom-file "$pwd"/pom.xml
```
> Update Generate command with optional param to create a pom xml file

- WORKSPACE
A dependency in the existing protobuf version (v3.8.0) is no longer
resolvable (zlip 1.2.10), bumping to a compatible semver release that
resolves this issue.
> Bump Protobuf to v3.20.1

- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
the gradle resolver code *looks* superficially like the other resolvers, but it actually is not the same and has a different (but very similarly named) code path.
Clearly we need more tests and also possibly rethink the design.
> Fix a bug in refactoring GradleResolver

- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
This is a follow up to: https://github.com/bazeltools/bazel-deps/pull/327
which made `-s` or `--sha-file` required as an option. We no longer use that so I had to make that optional again.
until we fix the CI:
```
oboykin@Oscars-MacBook-Pro bazel-deps % git rev-parse HEAD 
749b4dc151a9f01679f72666a5eaa645e53e09a8
oboykin@Oscars-MacBook-Pro bazel-deps % ./bazel test //...
DEBUG: Rule 'io_bazel_rules_scala' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1579112787 +0200"
DEBUG: Repository io_bazel_rules_scala instantiated at:
/Users/oboykin/code/bazel-deps/WORKSPACE:19:15: in <toplevel>
Repository rule git_repository defined at:
/private/var/tmp/_bazel_oboykin/4958ed22950b939e87bcc4e07cde8f11/external/bazel_tools/tools/build_defs/repo/git …
```
> Allow sha-file to be optional

- src/scala/com/github/johnynek/bazel_deps/Commands.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/ParseProject.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
We have developed a `check-only` option which only checks.
Unfortunately, it ignores many options and doesn't actually check everything. I think this is because the people who added the `check-only` only cared about certain options.
This will break people who are passing options to check-only that are currently ignored, but it may save people who thing more things are being checked than are.
A better solution is to have a check mode for everything, which instead of writing a file, makes sure that the file already exists and has been written. This could possibly be done with the IO abstraction we have already. In that mode, `rm` would do nothing, read would work as normal, but write would just fail unless we are writing the exact same file (maybe with some decent reporting of differences). …
> Validate options to error on ignored options

- src/scala/com/github/johnynek/bazel_deps/BUILD
- src/scala/com/github/johnynek/bazel_deps/CreatePom.scala
- src/scala/com/github/johnynek/bazel_deps/FS.scala
- src/scala/com/github/johnynek/bazel_deps/Label.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- src/scala/com/github/johnynek/bazel_deps/Target.scala
- src/scala/com/github/johnynek/bazel_deps/Writer.scala
- test/scala/com/github/johnynek/bazel_deps/BUILD
- test/scala/com/github/johnynek/bazel_deps/WriterGenerators.scala
This code is actually about file system abstraction, and not general modeling of side effects. It was written quite some time ago (2016 I think). That was before cats-effect was mature.
Now, cats-effect is one of the crown jewels of the scala ecosystem, and we should use that to better communicate which methods are running side effects vs not. So to prepare for that, we should rename this file system abstraction FS instead of IO.
> Rename IO to FS since it is about filesystem abstraction

- .github/workflows/release.yml
- ci_scripts/prepare_output.sh
this does 2 things:
1. bump to ubuntu 20.04 now that ubuntu 18.04 is no longer supported
2. publish the bazel-deps.jar deploy jar, so you can use that if the native-image doesn't work. For resolution, it may even be faster since that is a long process anyway.
> Fix release

- src/scala/com/github/johnynek/bazel_deps/GradleResolver.scala
- src/scala/com/github/johnynek/bazel_deps/MakeDeps.scala
- test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
- test/scala/com/github/johnynek/bazel_deps/CreatePomTest.scala
we never exercised a branch where the pwd wasn't already the repo-root, so we didn't see that it wouldn't work otherwise.
If you use a bazel run, the pwd in that case is the path to the binary so it will fail if you try to use bazel run with gradle.
> Make gradle lock files relative to the repo root

- src/scala/com/github/johnynek/bazel_deps/CreatePom.scala
- test/scala/com/github/johnynek/bazel_deps/CreatePomTest.scala
I left the MavenArtifactId class untouched to just fix this in CreatePom and avoid breaking other things that depend on that class. I wasn't able to get bazel to run tests for me(even on master), but confirmed that mvn was able to handle the classifier and type tags using the same format as what's in the updated CreatePomTest!
> CreatePom parsing update with maven type and classifier tags

- ci_scripts/make_native_artifact.sh
- ci_scripts/resource-config.json
Getting sometimes weird runtime errors from Graal bundle:
```
Could not load any resource bundle by com.sun.org.apache.xerces.internal.impl.msg.XMLMessages
```
Inspired by https://dplatz.de/blog/2020/quarkus-graalvm-reflection.html
> add explicit bundles for native-build

- src/scala/com/github/johnynek/bazel_deps/GradleLockDependency.scala
- src/scala/com/github/johnynek/bazel_deps/GradleLockFile.scala
- src/scala/com/github/johnynek/bazel_deps/GradleResolver.scala
This does two main things:
1. removes an annoying println in our logs about using VersionResolver. We have configured to use the "highest" conflict resolution. We don't need to println every time that runs. If we want to error, there is a VersionConflictPolicy for that: Fixed. I moved that println to a debug setting (which we can select with `--verbosity debug` to bazel-deps).
2. adds a bit more info logging to make sure deleted edges were being seen.
> Improve logging for gradle resolver
